name: web_emonit
description: Flutter Web Admin Emonit

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  cloud_firestore: ^3.1.7
  provider: ^6.0.2
  flutter_riverpod: ^1.0.3
  intl: ^0.17.0
  printing: ^5.7.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/logo_telkom.png
   - assets/admin.jpg
